### PR TITLE
add command to create or update Transactional Topic

### PR DESCRIPTION
**Pull request by xialeistudio**
Please do not create a Pull Request without creating an issue first. 

## What is the purpose of the change

Enrich document for beginners.

## Brief changelog

* add command to create transactional topic for beginners to learn how to operate transactional message.

## Verifying this change

No code changed.

### CODE REVIEW

**Comment by chenzlalvin** [comment]
Can you provide examples of creating advanced message types in other documents like fifo、delay and normal messageType.

**Review by tsunghanjacktsai — CHANGES_REQUESTED** [review]
Hey @xialeistudio ,

Thanks for your contribution to our website. Would you mind modify the English version of this part (https://github.com/apache/rocketmq-site/blob/new-official-website/i18n/en/docusaurus-plugin-content-docs/version-5.0/04-featureBehavior/04transactionmessage.md) as well? Appreciate it.

**Comment by xialeistudio** [comment]
> Can you provide examples of creating advanced message types in other documents like fifo、delay and normal messageType.

sure

**Comment by xialeistudio** [comment]
> Hey @xialeistudio ,
> 
> Thanks for your contribution to our website. Would you mind modify the English version of this part (https://github.com/apache/rocketmq-site/blob/new-official-website/i18n/en/docusaurus-plugin-content-docs/version-5.0/04-featureBehavior/04transactionmessage.md) as well? Appreciate it.

Sure, no problem.

**Review by tsunghanjacktsai — APPROVED** [review]
Great work.

**Review by tsunghanjacktsai — CHANGES_REQUESTED** [review]
Please resolve the conflicts between your branch and the `new-official-website` branch.

**Comment by xialeistudio** [comment]
> Please resolve the conflicts between your branch and the `new-official-website` branch.

done

**Review by RongtongJin — APPROVED** [review]

**Pull request merged**
